# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class Dashboard:
        type: str
        url: str
    class DatabaseMigrator:
        name: str
        type: str
    class Postgres:
        database: str
        host: str
        password: str
        port: float
        type: str
        username: str
    class Vpc:
        bastion: str
        type: str

